// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"768","screenHeight":"432","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"YEP_MessageCore","status":true,"description":"v1.02 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","Description Wrap":"false","---Font---":"","Font Name":"GameFont","Font Size":"18","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"Black_MessageBox","status":true,"description":"Enable a way to manually set the message window position.","parameters":{}},
{"name":"SOUL_HMCustomizer","status":true,"description":"A customizable simple menu for horror games. Version 2.0","parameters":{"Actor Bust Picture":"","Actor Bust X":"0","Actor Bust Y":"0","Menu Command X":"250","Menu Command Y":"120","Options Window X":"200","Options Window Y":"300","GameEnd Window X":"500","GameEnd Window Y":"200"}},
{"name":"Optionless","status":true,"description":"Remove options from the user","parameters":{}}
];
